services:
  wikiless:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wikiless
    hostname: wikiless
    restart: always
    networks:
      - wikiless_net
    environment:
      REDIS_HOST: redis://wikiless_redis:6379
    ports:
      - "127.0.0.1:8180:8080" # change port if needed
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    depends_on:
        - wikiless_redis

  wikiless_redis:
    image: redis:8-alpine
    container_name: wikiless_redis
    hostname: wikiless_redis
    restart: always
    networks:
      - wikiless_net
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./redis-data:/data
    user: redis
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  wikiless_net:
