version: "3.7"

services:
  wikiless:
    build: .
    restart: always
    networks:
      wikiless_net:
        ipv4_address: 172.4.0.6
    environment:
      REDIS_HOST: redis://172.4.0.5:6379
      THEME: dark  # change to light if you do not want dark by default
      HTTP_ADDR: 0.0.0.0 # don't touch
      DEFAULT_LANG: en # change to any language you want
      DOMAIN: changethis # set this to your domain do not add http://
      WIKIPAGE_CACHE_EXPIRATION: 3600
      wikimedia_useragent: Wikiless media proxy bot (https://github.com/Metastem/wikiless) 
    ports:
      - "127.0.0.1:8180:8080" # change port if needed
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
        - wikiless_redis

  wikiless_redis:
    image: "redis:alpine"
    restart: always
    networks:
      wikiless_net:
        ipv4_address: 172.4.0.5
    ports:
      - "6379"
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  wikiless_net:
    ipam:
      config:
        - subnet: 172.4.0.0/16
